// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn2tSEtjwsQ_3UKozmUnGWoDp5R-wieyg',
    appId: '1:300017735095:web:bdeadb9c1a9546987bc432',
    messagingSenderId: '300017735095',
    projectId: 'chat-app-cli',
    authDomain: 'chat-app-cli.firebaseapp.com',
    storageBucket: 'chat-app-cli.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8hSc0fNPzkskyHdGyPhBiku0ExFb5xE',
    appId: '1:300017735095:android:0a14480dafbb58427bc432',
    messagingSenderId: '300017735095',
    projectId: 'chat-app-cli',
    storageBucket: 'chat-app-cli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_34josvfdU_07OuCTadNoXASF5O0P4E',
    appId: '1:300017735095:ios:38a9be48ff69ee337bc432',
    messagingSenderId: '300017735095',
    projectId: 'chat-app-cli',
    storageBucket: 'chat-app-cli.firebasestorage.app',
    iosBundleId: 'com.example.chatAppCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_34josvfdU_07OuCTadNoXASF5O0P4E',
    appId: '1:300017735095:ios:38a9be48ff69ee337bc432',
    messagingSenderId: '300017735095',
    projectId: 'chat-app-cli',
    storageBucket: 'chat-app-cli.firebasestorage.app',
    iosBundleId: 'com.example.chatAppCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn2tSEtjwsQ_3UKozmUnGWoDp5R-wieyg',
    appId: '1:300017735095:web:ed8c4b1b07cf79397bc432',
    messagingSenderId: '300017735095',
    projectId: 'chat-app-cli',
    authDomain: 'chat-app-cli.firebaseapp.com',
    storageBucket: 'chat-app-cli.firebasestorage.app',
  );
}
